### ISSUE TITLE
node-fetch missing in dependency tree

### ISSUE THREAD

**Issue by onichandame** [vasco-santos/dns-over-http-resolver#44]
### Problem

This lib requires `native-fetch` which declares `node-fetch` as its peerDep. But `node-fetch` is not a dependency of this lib. Should we expect the app that depends on this lib to install `node-fetch` or should we have `node-fetch` in this lib's deps list?

**Comment by D4nte** [comment]
I think `node-fetch` should be added to this lib's dep list because the problem does exist when you use another lib that brings `dns-over-http-resolver` in.

For example, my project uses `multiaddr@10.0.1` and is facing the same issue:

```
/home/froyer/src/status-im/js-waku/node_modules/native-fetch/src/index.js
Cannot find module: 'node-fetch'. Make sure this package is installed.
```

**Comment by onichandame** [comment]
The multi-platform compatibility does make this harder to tackle. Axios and isomorphic-fetch are another 2 possible platform-agnostic tools that may help.
As I do not need to use this library anymore, I won't have enough time and testing cases for making a fix. The issue can be kept open to track the progress tho.
