### ISSUE TITLE
Invite web3-bot as a push-level collaborator to this repository

### ISSUE THREAD

**Issue by galargh** [vasco-santos/dns-over-http-resolver#74]
This is required to add Unified CI to this repository - https://github.com/protocol/.github/pull/356 cc @achingbrain 

web3-bot: https://github.com/web3-bot

**Comment by vasco-santos** [comment]
@galargh added it as collaborator. It was already added, but invite expired, so someone will need to accept on the other end to make it happen

**Comment by galargh** [comment]
Alright! Thanks, I'm on it!

**Comment by galargh** [comment]
https://github.com/vasco-santos/dns-over-http-resolver/pull/75 - uCI has been successfully deployed  :)
